* NumPy (Numerical Python) çok boyutlu diziler ve matrislerle çalışmamızı sağlayan, bilimsel hesaplamaları hızlı bir şekilde yapmamızı sağlayan bir matematik kütüphanesidir.
* NumPy geleneksel Python listelerinden 50 kata kadar daha hızlıdır.
* Python listlerinden farklı olarak NumPy dizileri homojen yapıda olmalıdır yani dizi içindeki tüm elemanlar aynı veri tipinde olmalıdır.
* Codebase olarak kısmen Python’da yazılmıştır ancak hızlı hesaplama gerektiren kısımların çoğu C ya da C++ ile yazılmıştır.

NumPy kütüphanesi Python dilinin doğrudan bir parçası değildir. Bu yüzden ayrıca kurulması ve program içerisinde tanımlanması yani import edilmesi gerekmektedir.

pip install numpy

In [35]:
import numpy as np

NumPy, daha çok dizilerle çalışmak amacıyla kullanılır. NumPy’daki dizi nesnesine ndarray adı verilir. Array() fonksiyonu kullanılarak bir NumPy ndarray nesnesi oluşturulur.

In [36]:
nd_array = np.array([1,2,4,5,6,7])
print(nd_array)

[1 2 4 5 6 7]


Bu şekilde bir liste üzerinden ndarray oluşturmuş olduk. Liste gibi tuple, set üzerinden de bir dizi oluşturabiliriz.

In [ ]:
tuple_nd = np.array((1,2,4,5,6,7))
print(nd_array)

**Dizilerde Boyutlar**

**0-D Diziler** -> İçerisinde tek bir değerin bulunduğudizilerdir.

In [5]:
nd_array = np.array(57)
print(nd_array)

57


**1-D Diziler** -> Elemanları 0-D dizileri olan tek boyutlu dizilerdir. Yaygın olarak kullanılan dizilerdir.

In [6]:
nd_array = np.array([1,2,3,4,5,7])
print(nd_array)

[1 2 3 4 5 7]


**2-D Diziler** -> Elemanları 1-D dizileri olan dizilerdir.

In [7]:
nd_array = np.array([[1,2,3,4,5,7], [2,3,4,5,6,7]])
print(nd_array)

[[1 2 3 4 5 7]
 [2 3 4 5 6 7]]


**3-D Diziler** -> Elemanları 2-D dizileri olan dizilerdir.

In [8]:
nd_array = np.array([[[1,2,3,4,5,7], [2,3,4,5,6,7]], [[1,2,3,4,5,7], [2,3,4,5,6,7]]])
print(nd_array)

[[[1 2 3 4 5 7]
  [2 3 4 5 6 7]]

 [[1 2 3 4 5 7]
  [2 3 4 5 6 7]]]


**Çok Boyutlu Diziler** -> Bir dizinin herhangi bir sayıda boyutu olabilir. Dizi oluşturulurken ndmin bağımsız değişkenini kullanarak boyut sayısını tanımlayabiliriz.

In [9]:
nd_array = np.array([1,2,3,4,5,7], ndmin=2)
print(nd_array)

[[1 2 3 4 5 7]]


**Boyut Sayısını Bulma**

**ndim** özelliği ile bir dizinin kaç boyuta sahip olduğu bilgisini alabiliriz.

In [10]:
nd = np.array(57)
nd_1d = np.array([1,2,3])
nd_2d = np.array([[1,2,3,7], [2,3,4,7]])
nd_3d = np.array([[[1,2,5,7], [2,3,6,7]], [[3,4,5,7], [2,3,4,5]]])
print(nd.ndim)
print(nd_1d.ndim)
print(nd_2d.ndim)
print(nd_3d.ndim)

0
1
2
3


**Dizinin satır ve sütun sayısını bulmak**

NumPy array nesnesinin kaç satır ve sütundan oluştuğunu .shape ile öğrenebiliriz. Dönüş olarak bir tuple nesnesi döndürür.

In [11]:
nd_1d = np.array([1,2,3,4,5,7])
nd_2d = np.array([[1,2,3,4,5,7], [2,3,4,5,6,7]])
print("1 boyutlu olan dizi  ", nd_1d.shape)
print("2 boyutlu olan dizi  ", nd_2d.shape)

1 boyutlu olan dizi   (6,)
2 boyutlu olan dizi   (2, 6)


**Dizinin satır ve sütun sayısını değiştirmek**

NumPy array’i yeniden şekillendirmek istediğimizde yani satır ve sütun sayısını değiştirmek istediğimizde .reshape metodunu kullanırız.

In [15]:
nd_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(nd_array)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
print(nd_array.reshape(5, 2))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


Başlangıçta numpy_array nesnemizin şekline baktığımızda(10,) olduğunu görüyoruz ve bu bize numpy_array nesnemizin tek boyutlu bir vektör olduğunu belirtir. reshape(5, 2) metodunu kullandığımızda ise artık numpy_array nesnemiz 5 satır ve 2 sütundan oluşan 5x2 lik 2 boyutlu bir matrise dönüşmüştür.

**np.arange()**

Python’daki range() fonksiyonuna benzer. Belirtilen başlangıç değerinden başlayıp, her seferinde adım sayısı kadar arttırarak, bitiş değerine kadar olan sayıları bulunduran bir numpy dizisi döndürür.

**np.arange(başlangıç, bitiş, adım sayısı)**

* Başlangıç değeri belirtilmezse varsayılan değer 0 kabul edilir.
* Bitiş değeri belirtilmezse dizinin uzunluğu varsayılan bitiş değeri kabul edilir.
* Basamak değeri belirtilmezse varsayılan değer 1 kabul edilir.

In [17]:
nd_array = np.arange(0, 10, 2)
print(nd_array)

[0 2 4 6 8]


**Dizi Elemanlarına Erişim**

*-* NumPy dizi elemanlarına indexler üzerinden erişiriz.

In [18]:
nd_array = np.array([1,2,3,4,5,7])
print(nd_array[3])

4


2 boyutlu olan bir dizide elemanlara erişelim

In [19]:
nd_array = np.array([[1,2,3,4,5,7], [2,3,4,5,6,7]])
print(nd_array[1, 3])

5


Listelerdeki gibi burada da negatif indexleme yapabiliriz.

In [20]:
print(nd_array[1, -1])

7


3 boyutlu olan bir dizide elemanlara erişelim

3 boyutlu dizilerde elemanlara erişmek için, elemanın boyutlarını ve dizinini temsil eden virgülle ayrılmış tamsayılar kullanabiliriz.

In [21]:
nd = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(nd[0, 1, 2])

6


**NumPy Slicing**

NumPy’da slicing, belirli bir indeksten belirli bir indekse kadar olan elemanları almak için kullanılır.

**[başlangıç, bitiş, adım sayısı]**

* Başlangıç değeri belirtilmezse varsayılan değer 0 kabul edilir.
* Bitiş değeri belirtilmezse dizinin uzunluğu varsayılan bitiş değeri kabul edilir.
* Basamak değeri belirtilmezse varsayılan değer 1 kabul edilir.

In [22]:
nd_1d = np.array([1,2,3,4,5,7])
print(nd_1d[:4])

[1 2 3 4]


In [23]:
nd_2d = np.array([[3,4,5,7], [2,5,6,7], [6,7,4,3]])
print(nd_2d[0:2, 1:4])

[[4 5 7]
 [5 6 7]]


**Dizilerde Veri Tipi**

dtype ile dizinin veri türünü öğreniriz.

In [24]:
nd = np.array([1,2,3,4,5,7])
print(nd.dtype)

int32


İstediğimiz boyutu eklemek için ndmin kullanıyorduk. Burada da istediğimiz veri tipini dizi elemanlarını oluştururken verebiliriz.

Yeni bir NumPy dizisi oluşturulduğunda, en uygun veri tipi NumPy tarafından seçilir. Ancak istenirse belirli bir veri tipi seçeneği verilebilir.

In [25]:
nd_array = np.array([1.2, 2.3, 3.3], dtype="i")
print(nd_1d)
print(nd_1d.dtype)

[1 2 3 4 5 7]
int32


np.zeros()

Bu fonksiyon belirtilen satır ve sütuna sahip 0'lardan oluşan bir matris döndürür.

In [48]:
print(np.zeros(2, 3))

[[0. 0. 0.]
 [0. 0. 0.]]


np.ones()

zeros() fonksiyonuna benzer şekilde verilen büyüklükte 1'lerden oluşan bir matris döndürür.

In [51]:
print(np.ones(2, 3))

[[1. 1. 1.]
 [1. 1. 1.]]


np.eye()

Belirlenen boyutlarda birim matris oluşturmamızı sağlar.

In [53]:
print(np.eye(3, 3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


np.random()

İstenilen boyutta bir dizin oluşturur ve bu dizini 0 ve 1 aralığında üretilmiş rastgele ondalık sayılar ile doldurur.

In [38]:
nd = np.random.random((3, 2))
print(nd)

[[0.77993657 0.97214158]
 [0.70732021 0.57933361]
 [0.33036706 0.36846497]]


linspace()

İki değer arasında eşit oranlı olacak şekilde değerler oluşturmak için kullanılır.

In [54]:
nd = np.linspace(5, 6, num=5)
print(nd)

[5.   5.25 5.5  5.75 6.  ]


Bu şekilde eşit aralıklarla istediğimiz iki sayı arasında istediğimiz sayıda elemandan oluşan bir dizi oluşturmuş olduk. Burada ardışık elemanlar arasındaki fark hepsinde aynıdır 0.25 oranında artmaktadır.

Burada num kullanmadan da yazabiliriz.

In [55]:
nd = np.linspace(5, 6, 5)
print(nd)

[5.   5.25 5.5  5.75 6.  ]


Burada belirlenen iki sayı arasında eşit aralıklarla elemanları oluştururken fark ettiğiniz gibi bitiş değerini de dahildir. Eğer dahil edilmesini istemiyorsak endpoint=False ekleyerek dahil etmeyebiliriz.

In [56]:
nd = np.linspace(5, 6, 5, endpoint=False)
print(nd)

[5.  5.2 5.4 5.6 5.8]


full()

Oluşturulacak dizinin elemanlarını aynı eleman ile doldurmak istediğimizde kullanırız. İlk parametrede kaça kaç olacağı ikinci parametrede de hangi değerle dolduracağımız bilgisini veririz.

In [57]:
nd = np.full((2, 3), 7)
print(nd)

[[7 7 7]
 [7 7 7]]


all()

Tüm elemanların verilen şartı sağlayıp sağlamadığını kontrol etmek için kullanılır.

In [58]:
nd = np.array([1,2,3])
np.all(nd < -1)

False

any()

Herhangi bir eleman verilen şartı sağlıyor mu diye kontrol etmek için kullanılır.

In [59]:
nd = np.array([1,-2,3])
np.any(nd < -1)

True

**Matrisleri birleştirmek**

İki numpy array nesnesini concatenate metodu ile birleştiririz.

In [60]:
nd1 = np.array([1,2,3])
nd2 = np.array([4,5,6])
nd3 = np.concatenate([nd1, nd2])
print(nd3)

[1 2 3 4 5 6]


İki numpy array nesnesini birleştirdiğimiz gibi bir liste ile de birleştirebiliriz. Ayrıca ikiden fazla değeri de birleştirebiliriz.

In [61]:
nd1 = np.array([1,2,3])
nd2 = np.array([4,5,6])
liste = [1,2,3,4,5]
nd3 = np.concatenate([nd1, nd2, liste])
print(nd3)

[1 2 3 4 5 6 1 2 3 4 5]


Integer değerlerden oluşan bir numpy arrayine içinde string ya da float olan bir liste ile birleştirirsek yeni oluşan numpy array o veri tipinde olacaktır.

In [62]:
nd1 = np.array([1, 2, 3])
liste = [5, 6, 4.5]
nd2 = np.concatenate([nd1, liste])
print(nd2)
print(nd2.dtype)

[1.  2.  3.  5.  6.  4.5]
float64


Satır sütun bazında birleştirme

In [63]:
nd1 = np.arange(0, 10)
nd1 = nd1.reshape(2, 5)
#Satır bazlı birleştirme
print(np.concatenate([nd1, nd1]))

[[0 1 2 3 4]
 [5 6 7 8 9]
 [0 1 2 3 4]
 [5 6 7 8 9]]


In [64]:
#Sütun bazlı birleştirme
print(np.concatenate([nd1, nd1], axis = 1))

[[0 1 2 3 4 0 1 2 3 4]
 [5 6 7 8 9 5 6 7 8 9]]


axis eklenmediği durumlarda default 0 kabul edilir ve satır bazlı birleştirme işlemi yapılır. axis = 1 sütun bazlı birleştirme işlemi yapar.

NumPy ile Matematiksel İşlemler
* sum
* max
* min
* mean
* median
* varyans
* standart sapma

In [65]:
numpy_array = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
numpy_array = numpy_array.reshape(5,2)

sum()

In [67]:
print(numpy_array.sum())
print("Satır bazlı toplama: ", numpy_array.sum(axis = 1))
print("Sütun bazlı toplama: ", numpy_array.sum(axis = 0))

45
Satır bazlı toplama:  [ 1  5  9 13 17]
Sütun bazlı toplama:  [20 25]


max()

In [68]:
print(numpy_array.max())

9


min()

In [69]:
print(numpy_array.min())

0


mean()

Dizinin ortalama değeridir.

In [70]:
print(numpy_array.mean())

4.5


standart sapma

Veri değerlerinin ortalamadan ne kadar uzak olduğunun ölçüsüdür. Standart sapma bize dağılımın yaygınlığı hakkında bilgi verir. Normal şartlarda standart sapmayı bulmak için sayıların aritmetik ortalaması bulunur. Her bir sayı aritmetik ortalamadan çıkarılır ve sonucun karesi alınır. Bu kareler toplanır ve toplam serinin eleman sayısının 1 eksiğine bölünür. Bu sonucun karekökü alınır. Standart sapmayı bulmak için bu işlemleri yapmamız gerekir fakat NumPy kütüphanesi np.std() fonksiyonuyla arka planda bu işlemleri yapar ve sonucu bize getirir.

In [71]:
print(numpy_array.std())

2.8722813232690143


varyans

Standart sapmanın karesidir.

In [72]:
print(numpy_array.var())

8.25


Varyans ve standart sapma veri setinde ortalama üzerinden karar veremeyeceğimiz durumlarda bize yardımcı olur.

**Aritmetik işlemler**

Aritmetik işlemleri yaparken unutulmaması gereken nokta işlem yapılacak matrislerin satır ve sütun sayılarının eşit olması gerekiyor.

In [73]:
nd1 = np.array([[1, 2], [3, 4]])
nd2 = np.array([[5, 6], [7, 8]])

#Toplama
print(nd1 + nd2) #np.add(nd1, nd2) aynı işlevde

[[ 6  8]
 [10 12]]


In [74]:
#Çıkarma
print(nd2 - nd1)   #np.subtract(nd2, nd1) aynı işlevde

[[4 4]
 [4 4]]


In [75]:
#Çarpma
print(nd2 * nd1)   #np.multiply(nd2, nd1) aynı işlevde

[[ 5 12]
 [21 32]]


In [76]:
#Bölme
print(nd2 / nd1)   #np.divide(nd2, nd1) aynı işlevde

[[5.         3.        ]
 [2.33333333 2.        ]]


İki matrisle işlem yaptığımız gibi matris elemanları üzerinde de istediğimiz sayı ile işlem yapabiliriz.

In [77]:
print(nd2 + 2) #Tüm elemanlara 2 ekledi

[[ 7  8]
 [ 9 10]]


NumPy toplama, çıkarma gibi basit dört işlemin yanısıra trigonometrik, logaritmik, üstel fonksiyonlar.. gibi daha kompleks fonksiyonlarla da çalışma imkanı sağlar.

**Matrislerin Çarpımı**

Matris çarpımı için dot fonksiyonunu kullanırız. İki matris çarpılırken ilk matrisin sütun sayısının ikinci matrisin satır sayısına eşit olması gerekiyor.

In [78]:
nd = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
nd1 = nd.reshape(5,2)
nd2 = nd.reshape(2,5)
print(np.dot(nd1, nd2))

[[  5   6   7   8   9]
 [ 15  20  25  30  35]
 [ 25  34  43  52  61]
 [ 35  48  61  74  87]
 [ 45  62  79  96 113]]


**Matrisin Transpozu**

Matrisin satırlarını sütun, sütunlarını satır yapma işlemi numpy ile “ .T” yazmak kadar kolay.

In [79]:
nd = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
nd = nd.reshape(5,2)
print(nd)
print(nd.T)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 2 4 6 8]
 [1 3 5 7 9]]
